---
abstract: 'configure Dist::Zilla the way BESSARABV does it'
author:
  - 'Ivan Bessarabov <ivan@bessarabov.ru>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-BESSARABV
requires:
  Dist::Zilla::Plugin::CheckChangesHasContent: 0
  Dist::Zilla::Plugin::Git: 0
  Dist::Zilla::Plugin::Git::ExcludeUntracked: 0
  Dist::Zilla::Plugin::GithubMeta: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::RunExtraTests: 0
resources:
  bugtracker: https://github.com/bessarabov/Dist-Zilla-PluginBundle-BESSARABV/issues
  homepage: https://github.com/bessarabov/Dist-Zilla-PluginBundle-BESSARABV
  repository: https://github.com/bessarabov/Dist-Zilla-PluginBundle-BESSARABV.git
version: 0.03
